// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe8wjAYGOlXmr2g_4N12rJw1W9pDAP91I',
    appId: '1:890791704389:web:2cdc5a50b17e97a6b6b02c',
    messagingSenderId: '890791704389',
    projectId: 'oauth-938b7',
    authDomain: 'oauth-938b7.firebaseapp.com',
    storageBucket: 'oauth-938b7.appspot.com',
    measurementId: 'G-EKLYQE3L96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3J61Auwjnfx3Q6gfAp9voxIAEDM9GANY',
    appId: '1:890791704389:android:f2d6f08a9aff264bb6b02c',
    messagingSenderId: '890791704389',
    projectId: 'oauth-938b7',
    storageBucket: 'oauth-938b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdGcoeYGe0VBMiWBlQPR-rQuRffv6-vHo',
    appId: '1:890791704389:ios:daea9bd4141fcc01b6b02c',
    messagingSenderId: '890791704389',
    projectId: 'oauth-938b7',
    storageBucket: 'oauth-938b7.appspot.com',
    iosBundleId: 'com.example.googleOauth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdGcoeYGe0VBMiWBlQPR-rQuRffv6-vHo',
    appId: '1:890791704389:ios:daea9bd4141fcc01b6b02c',
    messagingSenderId: '890791704389',
    projectId: 'oauth-938b7',
    storageBucket: 'oauth-938b7.appspot.com',
    iosBundleId: 'com.example.googleOauth',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBe8wjAYGOlXmr2g_4N12rJw1W9pDAP91I',
    appId: '1:890791704389:web:c5bf683e5ab565c1b6b02c',
    messagingSenderId: '890791704389',
    projectId: 'oauth-938b7',
    authDomain: 'oauth-938b7.firebaseapp.com',
    storageBucket: 'oauth-938b7.appspot.com',
    measurementId: 'G-Q0WNG7XNCS',
  );
}
